# Generated by Django 6.0.5 on 2026-05-25 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventsession',
            name='speaker',
            field=models.CharField(blank=True, default='speaker name', max_length=30),
        ),
        migrations.DeleteModel(
            name='Speaker',
        ),
    ]
