# Generated by Django 6.0.5 on 2026-05-25 05:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('community', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posteventfeedback',
            name='ticket',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='tickets.ticket'),
        ),
        migrations.AlterUniqueTogether(
            name='eventreview',
            unique_together={('event', 'author')},
        ),
        migrations.AlterUniqueTogether(
            name='networkingoptin',
            unique_together={('event', 'user')},
        ),
    ]
