# Generated by Django 6.0.5 on 2026-05-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aigenerationlog',
            name='gen_type',
            field=models.CharField(choices=[('description', 'Event Description Draft'), ('logo_prompt', 'Logo Generation Prompt'), ('schedule', 'Schedule Builder'), ('recommendation', 'Event Recommendation'), ('chatbot', 'Chatbot Response'), ('form_autofill', 'Form Autofill')], max_length=16),
        ),
    ]
